version: "3.9"

x-app: &default-app
  build: .

x-env: &env
  env_file:
    - .env

services:
  fastapi_parser:
    <<: [*default-app, *env]
    container_name: fastapi-parser-backend
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy

  db:
    <<: *env
    container_name: fastapi-parser-db
    image: postgres:15.3-alpine
    expose:
      - 5432
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - fastapiparserpg:/var/lib/postgresql/data

volumes:
  fastapiparserpg:
