"""Rename_fields_model_question

Revision ID: 0df0ac557b04
Revises: 2a253e8d1d0d
Create Date: 2023-10-21 13:54:57.515388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df0ac557b04'
down_revision: Union[str, None] = '2a253e8d1d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question', sa.String(), nullable=True))
    op.add_column('question', sa.Column('answer', sa.String(), nullable=True))
    op.drop_column('question', 'answer_text')
    op.drop_column('question', 'question_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('answer_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('question', 'answer')
    op.drop_column('question', 'question')
    # ### end Alembic commands ###
